service:
  id: "1"
  name: "echo"
  version: "1.0"
  addr: "localhost:9001"
  listen: ":9001"
  gwlisten: ":8001"

etcd:
  endpoints:
    - "localhost:2379"

jwt:
  sign: "echo"

log:
  filename: "./echo.log"
